


const products = [
    {
        id: 0,
        product_name: "Max Men Solid Crew Neck Lounge T-Shirt",
        price: 289,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product1-300x300.png",
        productNumber: 1,
        rating: 4,
    },
    {
        id: 1,
        product_name: "T-Max Men Solid Crew Neck Lounge T-Shirt",
        price: 149,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product2-300x300.png",
        productNumber: 1,
        rating: 3,
    },
    {
        id: 2,
        product_name: "Allen Solly Men's Regular Fit Polo",
        price: 299,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product3-300x300.png",
        productNumber: 1,
        rating: 3.5,
    },
    {
        id: 3,
        product_name: "Max Men Textured Slim Fit Structured T-Shirt",
        price: 299,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product4-300x300.png",
        productNumber: 1,
        rating: 4.3,
    },
    {
        id: 4,
        product_name: "Lavie Women's Oval Frame Clutch | Ladies Purse Wallet",
        price: 899,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product5.png",
        productNumber: 1,
        rating: 4.5,
    },
    {
        id: 5,
        product_name: "AUSHA® 16MP 4K HD Digital Action Camera Supports HDMI",
        price: 2635,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product6.png",
        productNumber: 1,
        rating: 5,
    },
    {
        id: 6,
        product_name: "Sonata Analog Women's Watch",
        price: 610,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product7.png",
        productNumber: 1,
        rating: 4.1
    },
    {
        id: 7,
        product_name: "Max Men Solid Crew Neck Lounge T-Shirt",
        price: 349,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product1-300x300.png",
        productNumber: 1,
        rating: 4.8,
    },
    {
        id: 8,
        product_name: "Miss & Mam Professional Makeup Set Brusher",
        price: 399,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product9.jpg",
        productNumber: 1,
        rating: 4.7,
    },
    {
        id: 9,
        product_name: "Maybelline New York Matte Lipstick, Intense Colour",
        price: 174,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product10.png",
        productNumber: 1,
        rating: 4.6,
    },
    {
        id: 10,
        product_name: "Colourful Glass Marble Balls for Playing Games",
        price: 278,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product11.png",
        productNumber: 1,
        rating: 4.2,
    },
    {
        id: 11,
        product_name: "Whimsy Blossom Beauty Kit Complete Makeup set",
        price: 999,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product12.png",
        productNumber: 1,
        rating: 3.3,
    },
    {
        id: 12,
        product_name: "Analog Wrist Watch, Stylish Wired Metal Mesh Band",
        price: 999,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product13.png",
        productNumber: 1,
        rating: 3.4,
    },
    {
        id: 13,
        product_name: "Fire-Boltt Ninja Call Pro Smart Watch Dual Chip, 1.69",
        price: 1299,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product14.png",
        productNumber: 1,
        rating: 4.9,
    },
    {
        id: 14,
        product_name: "AIRSON Jaguar Sports Shoes for Men",
        price: 550,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product15.png",
        productNumber: 1,
        rating: 3.8,
    },
    {
        id: 15,
        product_name: "CHANNAPATNA TOYS BY MEERAN ART AND CRAFTS",
        price: 417,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product16.jpg",
        productNumber: 1,
        rating: 3.9,
    },
    {
        id: 16,
        product_name: "boAt Xtend Smart Watch with Alexa Built-in, 1.69",
        price: 1699,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product17.png",
        productNumber: 1,
        rating: 4.1,
    },
    {
        id: 17,
        product_name: "AIRSON Jaguar Sports Shoes for Men",
        price: 749,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product18.png",
        productNumber: 1,
        rating: 3.9,
    },
    {
        id: 18,
        product_name: "AIRSON Jaguar Sports Shoes for Men",
        price: 699,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product19.png",
        productNumber: 1,
        rating: 2,
    },
    {
        id: 19,
        product_name: "Minimalist 2% Salicylic Acid Serum For Acne & Open Pores",
        price: 521,
        description:"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum, dicta!",
        available: true,
        imgSrc: "img/product20.png",
        productNumber: 1,
        rating: 2.6,
    },










    ]